export const USER_SIGNUP = 'USER_SIGNUP';
export const USER_LOGIN = 'USER_LOGIN';
export const USER_SIGNOUT = 'USER_SIGNOUT';
export const USER_UPDATE = 'USER_UPDATE';
export const GET_USER = 'GET_USER';

export const UPDATE_FAILED = 'UPDATE_FAILED';
export const AUTH_ERROR = 'AUTH_ERROR';
export const CLEAR_AUTH_ERROR = 'CLEAR_AUTH_ERROR';
export const REGISTER_ERROR = 'REGISTER_ERROR';
export const LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_LOGIN_ERROR = 'LOGIN_ERROR';
export const CLEAR_LOGIN_MESSAGE = 'LOGIN_MESSAGE';
export const CLEAR_REGISTER_ERROR = 'CLEAR_REGISTER_ERROR';
export const CLEAR_SIGNUP_MESSAGE = 'CLEAR_SIGNUP_MESSAGE';
export const ACTIVATE_SUCCESS = 'ACTIVATE_SUCCESS';
export const ACTIVATE_FAILED = 'ACTIVATE_FAILED';

export const RESET_PASSWORD = 'RESET_PASSWORD';
export const RESET_PASSWORD_ERROR = 'RESET_PASSWORD_ERROR';
export const FORGOT_PASSWORD = 'FORGOT_PASSWORD';
export const FORGOT_PASSWORD_ERROR = 'FORGOT_PASSWORD_ERROR';
export const CLEAR_FORGOT_PASSWORD_ERROR = 'CLEAR_FORGOT_PASSWORD_ERROR';

export const UI_LOADING = 'UI_LOADING';
export const CLEAR_LOADING = 'CLEAR_LOADING';

export const serverURL = 'http://localhost:8000';
